### ISSUE TITLE
No output is recorded when bin/sim_run is activated

### ISSUE THREAD

**Issue by Roclemir** [RMIT-RoboCup-Standard-League/PP1-Nao-Soccer#15]
The file in rUNSWift/bin/sim_run (which needs to be called while in the rUNSWift/ directory) basically calls rUNSWift/buiild-release/robot/runswift the specified number of times (if no arguments given, then calls it for team 18, 5 times). 
The output from each instantiated simulated robot is piped to /dev/null, ie: the output is lost. 

It would be good if the output from each instantiated simulated robot could be piped to a log file for analysis if anything goes wrong. 
These log files need only be pertinent for the latest run, and therefore the folder containing the log files can be wiped at the start of each new run of sim_run.

**Comment by ranlu302** [comment]
Hi Ryan, since the log info will be shown when using runswift, do we still need to view log message of sim_run?

**Comment by Roclemir** [comment]
We still don't get any output from using sim_run. If you were testing team dynamics, this would be a helpful feature.
