### ISSUE TITLE
Behaviour exception when sending a behaviour command to the simulated robot

### ISSUE THREAD

**Issue by ranlu302** [RMIT-RoboCup-Standard-League/PP1-Nao-Soccer#18]
Firstly, both Simspark server and a monitor, either Simspark monitor or Roboviz need to be running in the VM. To send a behaviour command to simswift, I used rUNSWift/build-release/robot/runswift -s WalkTest. Then the robot fell down and tried to get up several times with continuous error messages in the terminal.

<img width="1110" alt="untitled" src="https://user-images.githubusercontent.com/20898972/35867301-8e3bf7fa-0bad-11e8-8461-24c33947c352.png">

Although all behaviour files are in image/home/nao/data/test, the message above shows that either no enough arguments for the string or no module in role or skill.

**Comment by ranlu302** [comment]
To test a behaviour in the monitor, we need to do the following steps:
1. Add python scripts of behaviours to rUNSWift/image/home/nao/data/behaviours/skills (e.g. some test scripts are in rUNSWift/image/home/nao/data/behaviours/test, you can copy and paste them into skills folder). 
2. Run the server and the monitor by the command:
rcsoccersim3d
3. Initiate simswift instances in the terminal and send behavior command:
rUNSWift/build-release/robot/runswift -n 5 -T 22 -s WalkAround
The last command line argument need to match the python file name you put in the skills folder, you can modify player number and team number here, the default would be team 19 player 1 without first two arguments.

**Comment by Roclemir** [comment]
Ran, could you please clarify what step 1 means?
It says "Add python scripts of behaviours in ..."
Do you mean you want us to add python scripts of behaivours to the folder "rUNSWift/image/home..."" or do you mean you want us to get the scripts from the folder you mentioned and put them somewhere else? Or do you mean run some special command so the python scripts are loaded into somewhere?

**Comment by ranlu302** [comment]
Yep, some test scripts are in rUNSWift/image/home/nao/data/behaviours/test, you can copy and paste them into skills folder and use runswift -s WalkAround. You can add your own python scripts skills as well.

**Comment by Louis-Stekhoven-Smith** [comment]
Copying files over is a hack fix the issue was to do with the import pathway for the test folder. 

Fixed the issue by renaming the test/ folder to tests/ and updating behavior.py as required. 

Can now call test behaviors without having to copy files over to the skills folder.
