### ISSUE TITLE
Offnao - Getting Segfault when attempting to start Offnao

### ISSUE THREAD

**Issue by Roclemir** [RMIT-RoboCup-Standard-League/PP1-Nao-Soccer#2]
You will need:
rUNSWift codebase installed and built, 
roboviz installed (including simpspark).

Steps to reproduce:
1. Fire up the simulator server and monitor by entering "rcsoccersim3d" at the command line terminal

2. Open a new terminal and enter "sudo rUNSWift/build-release/robot/runswift [-n num] [-T team]" to add a new agent to the server.

3. Open up a new terminal (again) and enter "./'build directory'/utils/offnao/offnao" to start Offnao.
^^ This is the step that fires off a segfault.

**Comment by Roclemir** [comment]
Found some instructions regarding this fault in ~/rUNSWift/utils/offnao/README
Here's a screenshot:
![image](https://user-images.githubusercontent.com/35439984/35324511-05447462-0145-11e8-826f-6d392e8f9102.png)
I am attempting to follow (the somewhat vague) workaround now.

**Comment by Roclemir** [comment]
Unfortunately their "instructions" don't specify what folder to be in when typing these commands and creating build folders randomly and typing "make" would prove fruitless.

**Comment by Roclemir** [comment]
I've worked out that the commands need to be run in the directory 
~/rUNSWift/utils/offnao

However, as it states in the above instructions, I need to get QT4 and some other things. Will report back when I figure out what "QT4" actually is.

**Comment by Roclemir** [comment]
Its a C++ framework.
Install from command line with
sudo apt-get install qt4-dev-tools

**Comment by Roclemir** [comment]
After qt4-dev-tools installation, the error persists.
... back to the drawing board.

**Comment by Louis-Stekhoven-Smith** [comment]
did you run the make to build the new binary's?

**Comment by Roclemir** [comment]
I'm not sure what you mean, I only installed qt4, I didn't change the software.
Should I build the whole thing again?

**Comment by ghost** [comment]
Offnao isn't compiled by build_setup. I've found qt5 is recommended in that file, how about upgrading to qt5?

**Comment by Roclemir** [comment]
I rebuilt the whole thing. Didn't fix the issue.

In regards to qt5, qt4_add_resources is hard coded into the cmake file:
![screen shot 2018-01-24 at 9 50 40 pm](https://user-images.githubusercontent.com/35439984/35328504-afccb042-0150-11e8-8fca-6c78152ccab5.png)

Not saying it can't be changed, just saying it's baked in.

**Comment by ghost** [comment]
I have the issue when running the readme instruction, have you got this error? Qt4 was installed.
<img width="904" alt="123" src="https://user-images.githubusercontent.com/35696170/35330593-2e6dbdea-0158-11e8-8eec-3de27775d5d8.png">

**Comment by Roclemir** [comment]
yes, that's the error I get.

**Comment by Roclemir** [comment]
Issue solved.

To resolve on your systems, instal qt4-dev-tools with
sudo apt-get install qt4-dev-tools
Then you will need to pull my merge (after my merge request is approved). 
@ranlu90 can you please add this package to the list of packages that are required to be installed in the getting started document. Thanks.

A few lines of code were missing from the CMakeLists.txt file, specifically:
set(CMAKE_AUTOMOC ON)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
find_package(Qt4 4.4.3 REQUIRED QtGui QtXml)

I have fixed it in the bug branch, I will create a pull request for it.

This has led directly to another issue, but we'll get over that soon.

**Comment by Roclemir** [comment]
Adding the abode lines to rUNSWift/utils/offnao/CMakeLists.txt worked for Offnao only, but it breaks the original build in ~/rUNSWift/bin/build_setup.sh

**Comment by Roclemir** [comment]
Managed to fix it by wrapping that particular three lines of CMake code into an if package found statement.

**Comment by Roclemir** [comment]
I'm just fixing a couple of syntax errors, will create pull request shortly.

**Comment by Roclemir** [comment]
NOTE: After applying this fix, you need to go back and rebuild all by being in the ~/rUNSWift/ folder and typing bin/build_setup.sh

**Comment by ghost** [comment]
The error has been fixed here.
Issue #7
