### ISSUE TITLE
Cmake error building offnao - cannot find cotire

### ISSUE THREAD

**Issue by Roclemir** [RMIT-RoboCup-Standard-League/PP1-Nao-Soccer#4]
When building Offnao with cmake in after applying fix from issue #2, following the instructions in the  ~/rUNSWift/utils/offnao/README file, when typing the cmake .. command, the following error appears:
![screen shot 2018-01-25 at 11 10 56 am](https://user-images.githubusercontent.com/35439984/35363891-7c23ecd6-01c0-11e8-8899-0da76d7c5fc8.png)

Perhaps another missing find_<package> command?

**Comment by ghost** [comment]
Some environment variables were not set properly in this file and add the following lines in the beginning may solve the issue.
include(cotire)
set (PNG_PNG_INCLUDE_DIR "${CTC_DIR}/png/include")
set (PNG_LIBRARY "${CTC_DIR}/png/lib")
set (QGLVIEWER_LIBRARY "$(RUNSWIFT_CHECKOUT_DIR)/ctc/sysroot_legacy/usr/include/QGLViewer")

**Comment by ghost** [comment]
If include(cotire) shows error the following one should be added.
set (CMAKE_MODULE_PATH "/home/ubuntu/rUNSWift/CMake")

**Comment by Roclemir** [comment]
I think the issue is bigger than the rUNSWift/utils/offnao/CMakeLists.txt file
After this fix I created, I tried to run bin/build_setup.sh again and that build failed at the line "find_package(...)" that I added into the offnao's CMakeLists.txt. So I don't think the fix I found is correct.

**Comment by Roclemir** [comment]
Ooops, didn't mean to close it.

**Comment by Roclemir** [comment]
Added the suggested lines which fixed the cotire issue, but now bin/build_setup.sh is broken again.

**Comment by Roclemir** [comment]
Added the lines inside the if statement created for the Qt4 issue.

It seems that Qt4 and cotire are loaded correctly when bin/build_setup.sh is run. But when offnao needs to be built on its own, they aren't loaded.
