### ISSUE TITLE
Not a directory issue when running runswift or sim_run

### ISSUE THREAD

**Issue by ghost** [RMIT-RoboCup-Standard-League/PP1-Nao-Soccer#8]
The issue has been found when using the above command. If using runswift, the error message would show /var/voliatile/runswift/Visualiser is not a directory and terminated. If using sim_run, the simulated instances will not be showed in the Roboviz monitor. A simple solution is to delete Visualiser if error occurs, but further improvements might be available and change Log.py.

![3](https://user-images.githubusercontent.com/35696170/35490570-a8fc5fae-04f4-11e8-942b-a69185253773.PNG)

**Comment by Louis-Stekhoven-Smith** [comment]
We can do a quick hack fix to check if last file is 'Visualiser' get second last file instead. But should really rewrite the base run swift code to make it more robust. I'll fix this.
